### ISSUE TITLE
[TASK] Create prototype client which can be used to submit queries

### ISSUE THREAD

**Issue by ls-1801** [nebulastream/nebulastream#131]
### Description

Currently, the SingleNodeWorker only exposes a GRPC Interface, which is expected to be a Fully Specified Logical Query Plan.

This issue tracks the prototyping of a command line tool that generates and submits FS-LQP to the Worker Node. The generation is based on existing functionality extracted from the coordinator:

1. Parses the C++ Query
2. Resolves and expands logical sources
3. Applies mandatory inference phases
4. Submits the query via GRPC to the Worker

The Tool expects a Query Specification like:

```yaml
query: Query::from("logical")...sink(PrintSink::create());
logical:
  - name: "logical"
    fields:
      - name: "a"
        type: "UINT32"
physical:
  - logical: "logical"
    config:
      - type: "TCP"
```
